version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: graduation_thesis
    entrypoint: ["tini", "-g", "--", "/startup/docker-entrypoint.sh", "neo4j"]
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/Abc12345
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms.security.procedures.allowlist=apoc.*
      - NEO4J_AUTH=neo4j/Abc12345
      - NEO4JLABS_PLUGINS=["apoc"]
      - JAVA_HOME=/opt/java/openjdk
      - NEO4J_SHA256=7e16dc4f2c43bc188a358b47c5fad9d0300f1fb2d5998e65380fe425dd8af6d6
      - NEO4J_TARBALL=neo4j-community-5.24.2-unix.tar.gz
      - NEO4J_EDITION=community
      - NEO4J_HOME=/var/lib/neo4j
    volumes:
      - ./database/neo4j/data:/data
      - ./database/neo4j/logs:/logs
      - ./database/neo4j/config:/config
      - ./database/neo4j/plugins:/plugins
    restart: always
  
  qdrant:
    image: qdrant/qdrant
    container_name: graduation_thesis_qdrant
    volumes:
      - ./database/qdrant:/qdrant/storage
    ports:
      - "6333:6333"
